package com.mark.manager.mapper;

import com.mark.manager.pojo.VproCoursesLessonList;
import com.mark.manager.pojo.VproCoursesLessonListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproCoursesLessonListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    long countByExample(VproCoursesLessonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    int deleteByExample(VproCoursesLessonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    int deleteByPrimaryKey(Integer lessonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    int insert(VproCoursesLessonList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    int insertSelective(VproCoursesLessonList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    List<VproCoursesLessonList> selectByExample(VproCoursesLessonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    VproCoursesLessonList selectByPrimaryKey(Integer lessonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") VproCoursesLessonList record, @Param("example") VproCoursesLessonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    int updateByExample(@Param("record") VproCoursesLessonList record, @Param("example") VproCoursesLessonListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    int updateByPrimaryKeySelective(VproCoursesLessonList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_lesson_list
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    int updateByPrimaryKey(VproCoursesLessonList record);
}