package com.mark.manager.mapper;

import com.mark.manager.pojo.VproCoursesContent;
import com.mark.manager.pojo.VproCoursesContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproCoursesContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    long countByExample(VproCoursesContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int deleteByExample(VproCoursesContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int insert(VproCoursesContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int insertSelective(VproCoursesContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    List<VproCoursesContent> selectByExampleWithBLOBs(VproCoursesContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    List<VproCoursesContent> selectByExample(VproCoursesContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    VproCoursesContent selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") VproCoursesContent record, @Param("example") VproCoursesContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") VproCoursesContent record, @Param("example") VproCoursesContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int updateByExample(@Param("record") VproCoursesContent record, @Param("example") VproCoursesContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int updateByPrimaryKeySelective(VproCoursesContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(VproCoursesContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    int updateByPrimaryKey(VproCoursesContent record);
}