package com.mark.manager.mapper;

import com.mark.manager.pojo.VproCoursesTempDetail;
import com.mark.manager.pojo.VproCoursesTempDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproCoursesTempDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    long countByExample(VproCoursesTempDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    int deleteByExample(VproCoursesTempDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    int deleteByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    int insert(VproCoursesTempDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    int insertSelective(VproCoursesTempDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    List<VproCoursesTempDetail> selectByExample(VproCoursesTempDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    VproCoursesTempDetail selectByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") VproCoursesTempDetail record, @Param("example") VproCoursesTempDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    int updateByExample(@Param("record") VproCoursesTempDetail record, @Param("example") VproCoursesTempDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    int updateByPrimaryKeySelective(VproCoursesTempDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses_temp_detail
     *
     * @mbg.generated Fri Oct 26 15:30:29 CST 2018
     */
    int updateByPrimaryKey(VproCoursesTempDetail record);
}