package com.mark.manager.mapper;

import com.mark.manager.pojo.VproOrderSub;
import com.mark.manager.pojo.VproOrderSubExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproOrderSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    long countByExample(VproOrderSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    int deleteByExample(VproOrderSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    int deleteByPrimaryKey(Integer orderSubId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    int insert(VproOrderSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    int insertSelective(VproOrderSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    List<VproOrderSub> selectByExample(VproOrderSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    VproOrderSub selectByPrimaryKey(Integer orderSubId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") VproOrderSub record, @Param("example") VproOrderSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    int updateByExample(@Param("record") VproOrderSub record, @Param("example") VproOrderSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    int updateByPrimaryKeySelective(VproOrderSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order_sub
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    int updateByPrimaryKey(VproOrderSub record);
}