package com.mark.manager.mapper;

import com.mark.manager.pojo.VproComment;
import com.mark.manager.pojo.VproCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    long countByExample(VproCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    int deleteByExample(VproCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    int deleteByPrimaryKey(Integer vproCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    int insert(VproComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    int insertSelective(VproComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    List<VproComment> selectByExample(VproCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    VproComment selectByPrimaryKey(Integer vproCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") VproComment record, @Param("example") VproCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    int updateByExample(@Param("record") VproComment record, @Param("example") VproCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    int updateByPrimaryKeySelective(VproComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    int updateByPrimaryKey(VproComment record);
}