package com.mark.manager.mapper;

import com.mark.manager.pojo.VproVideo;
import com.mark.manager.pojo.VproVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    long countByExample(VproVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    int deleteByExample(VproVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    int deleteByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    int insert(VproVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    int insertSelective(VproVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    List<VproVideo> selectByExample(VproVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    VproVideo selectByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") VproVideo record, @Param("example") VproVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    int updateByExample(@Param("record") VproVideo record, @Param("example") VproVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    int updateByPrimaryKeySelective(VproVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    int updateByPrimaryKey(VproVideo record);
}