package com.mark.manager.mapper;

import com.mark.manager.pojo.VproNavbar;
import com.mark.manager.pojo.VproNavbarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproNavbarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    long countByExample(VproNavbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int deleteByExample(VproNavbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int deleteByPrimaryKey(Integer navId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int insert(VproNavbar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int insertSelective(VproNavbar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    List<VproNavbar> selectByExample(VproNavbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    VproNavbar selectByPrimaryKey(Integer navId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") VproNavbar record, @Param("example") VproNavbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int updateByExample(@Param("record") VproNavbar record, @Param("example") VproNavbarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int updateByPrimaryKeySelective(VproNavbar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_navbar
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int updateByPrimaryKey(VproNavbar record);
}