package com.mark.manager.mapper;

import com.mark.manager.pojo.VproCommentSupportRate;
import com.mark.manager.pojo.VproCommentSupportRateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproCommentSupportRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    long countByExample(VproCommentSupportRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    int deleteByExample(VproCommentSupportRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    int insert(VproCommentSupportRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    int insertSelective(VproCommentSupportRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    List<VproCommentSupportRate> selectByExample(VproCommentSupportRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    VproCommentSupportRate selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") VproCommentSupportRate record, @Param("example") VproCommentSupportRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    int updateByExample(@Param("record") VproCommentSupportRate record, @Param("example") VproCommentSupportRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    int updateByPrimaryKeySelective(VproCommentSupportRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_comment_support_rate
     *
     * @mbg.generated Thu Mar 07 23:35:45 CST 2019
     */
    int updateByPrimaryKey(VproCommentSupportRate record);
}