package com.mark.manager.mapper;

import com.mark.manager.pojo.VproAuth;
import com.mark.manager.pojo.VproAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    long countByExample(VproAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int deleteByExample(VproAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int deleteByPrimaryKey(Integer authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int insert(VproAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int insertSelective(VproAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    List<VproAuth> selectByExample(VproAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    VproAuth selectByPrimaryKey(Integer authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") VproAuth record, @Param("example") VproAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int updateByExample(@Param("record") VproAuth record, @Param("example") VproAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int updateByPrimaryKeySelective(VproAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_auth
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    int updateByPrimaryKey(VproAuth record);
}