package com.mark.manager.mapper;

import com.mark.manager.pojo.VproOrder;
import com.mark.manager.pojo.VproOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    long countByExample(VproOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    int deleteByExample(VproOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    int insert(VproOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    int insertSelective(VproOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    List<VproOrder> selectByExample(VproOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    VproOrder selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") VproOrder record, @Param("example") VproOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    int updateByExample(@Param("record") VproOrder record, @Param("example") VproOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    int updateByPrimaryKeySelective(VproOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_order
     *
     * @mbg.generated Thu Feb 28 12:48:35 CST 2019
     */
    int updateByPrimaryKey(VproOrder record);
}