package com.mark.manager.mapper;

import com.mark.manager.pojo.VproPermissions;
import com.mark.manager.pojo.VproPermissionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    long countByExample(VproPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int deleteByExample(VproPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int deleteByPrimaryKey(Integer permissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int insert(VproPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int insertSelective(VproPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    List<VproPermissions> selectByExample(VproPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    VproPermissions selectByPrimaryKey(Integer permissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") VproPermissions record, @Param("example") VproPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByExample(@Param("record") VproPermissions record, @Param("example") VproPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByPrimaryKeySelective(VproPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByPrimaryKey(VproPermissions record);
}