package com.mark.manager.mapper;

import com.mark.manager.pojo.VproRoles;
import com.mark.manager.pojo.VproRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    long countByExample(VproRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int deleteByExample(VproRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int deleteByPrimaryKey(Integer rolesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int insert(VproRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int insertSelective(VproRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    List<VproRoles> selectByExample(VproRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    VproRoles selectByPrimaryKey(Integer rolesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") VproRoles record, @Param("example") VproRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByExample(@Param("record") VproRoles record, @Param("example") VproRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByPrimaryKeySelective(VproRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByPrimaryKey(VproRoles record);
}