package com.mark.manager.mapper;

import com.mark.manager.pojo.VproRolesPermissions;
import com.mark.manager.pojo.VproRolesPermissionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VproRolesPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    long countByExample(VproRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int deleteByExample(VproRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int deleteByPrimaryKey(Integer rolesPermissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int insert(VproRolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int insertSelective(VproRolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    List<VproRolesPermissions> selectByExample(VproRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    VproRolesPermissions selectByPrimaryKey(Integer rolesPermissionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") VproRolesPermissions record, @Param("example") VproRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByExample(@Param("record") VproRolesPermissions record, @Param("example") VproRolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByPrimaryKeySelective(VproRolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_roles_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    int updateByPrimaryKey(VproRolesPermissions record);
}