package com.mark.manager.pojo;

import java.math.BigDecimal;

public class VproOrderSub {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_sub.order_sub_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    private Integer orderSubId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_sub.order_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_sub.course_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_sub.course_price
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    private BigDecimal coursePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_sub.user_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_sub.order_sub_id
     *
     * @return the value of vpro_order_sub.order_sub_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public Integer getOrderSubId() {
        return orderSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_sub.order_sub_id
     *
     * @param orderSubId the value for vpro_order_sub.order_sub_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public void setOrderSubId(Integer orderSubId) {
        this.orderSubId = orderSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_sub.order_id
     *
     * @return the value of vpro_order_sub.order_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_sub.order_id
     *
     * @param orderId the value for vpro_order_sub.order_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_sub.course_id
     *
     * @return the value of vpro_order_sub.course_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_sub.course_id
     *
     * @param courseId the value for vpro_order_sub.course_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_sub.course_price
     *
     * @return the value of vpro_order_sub.course_price
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public BigDecimal getCoursePrice() {
        return coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_sub.course_price
     *
     * @param coursePrice the value for vpro_order_sub.course_price
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public void setCoursePrice(BigDecimal coursePrice) {
        this.coursePrice = coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_sub.user_id
     *
     * @return the value of vpro_order_sub.user_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_sub.user_id
     *
     * @param userId the value for vpro_order_sub.user_id
     *
     * @mbg.generated Sat Mar 02 20:48:23 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}