package com.mark.manager.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class VproCoursesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public VproCoursesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(Integer value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(Integer value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(Integer value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(Integer value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(Integer value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<Integer> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<Integer> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(Integer value1, Integer value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseTitleIsNull() {
            addCriterion("course_title is null");
            return (Criteria) this;
        }

        public Criteria andCourseTitleIsNotNull() {
            addCriterion("course_title is not null");
            return (Criteria) this;
        }

        public Criteria andCourseTitleEqualTo(String value) {
            addCriterion("course_title =", value, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleNotEqualTo(String value) {
            addCriterion("course_title <>", value, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleGreaterThan(String value) {
            addCriterion("course_title >", value, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleGreaterThanOrEqualTo(String value) {
            addCriterion("course_title >=", value, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleLessThan(String value) {
            addCriterion("course_title <", value, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleLessThanOrEqualTo(String value) {
            addCriterion("course_title <=", value, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleLike(String value) {
            addCriterion("course_title like", value, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleNotLike(String value) {
            addCriterion("course_title not like", value, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleIn(List<String> values) {
            addCriterion("course_title in", values, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleNotIn(List<String> values) {
            addCriterion("course_title not in", values, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleBetween(String value1, String value2) {
            addCriterion("course_title between", value1, value2, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCourseTitleNotBetween(String value1, String value2) {
            addCriterion("course_title not between", value1, value2, "courseTitle");
            return (Criteria) this;
        }

        public Criteria andCoursePidIsNull() {
            addCriterion("course_pid is null");
            return (Criteria) this;
        }

        public Criteria andCoursePidIsNotNull() {
            addCriterion("course_pid is not null");
            return (Criteria) this;
        }

        public Criteria andCoursePidEqualTo(Integer value) {
            addCriterion("course_pid =", value, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCoursePidNotEqualTo(Integer value) {
            addCriterion("course_pid <>", value, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCoursePidGreaterThan(Integer value) {
            addCriterion("course_pid >", value, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCoursePidGreaterThanOrEqualTo(Integer value) {
            addCriterion("course_pid >=", value, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCoursePidLessThan(Integer value) {
            addCriterion("course_pid <", value, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCoursePidLessThanOrEqualTo(Integer value) {
            addCriterion("course_pid <=", value, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCoursePidIn(List<Integer> values) {
            addCriterion("course_pid in", values, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCoursePidNotIn(List<Integer> values) {
            addCriterion("course_pid not in", values, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCoursePidBetween(Integer value1, Integer value2) {
            addCriterion("course_pid between", value1, value2, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCoursePidNotBetween(Integer value1, Integer value2) {
            addCriterion("course_pid not between", value1, value2, "coursePid");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorIsNull() {
            addCriterion("course_author is null");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorIsNotNull() {
            addCriterion("course_author is not null");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorEqualTo(String value) {
            addCriterion("course_author =", value, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorNotEqualTo(String value) {
            addCriterion("course_author <>", value, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorGreaterThan(String value) {
            addCriterion("course_author >", value, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("course_author >=", value, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorLessThan(String value) {
            addCriterion("course_author <", value, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorLessThanOrEqualTo(String value) {
            addCriterion("course_author <=", value, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorLike(String value) {
            addCriterion("course_author like", value, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorNotLike(String value) {
            addCriterion("course_author not like", value, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorIn(List<String> values) {
            addCriterion("course_author in", values, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorNotIn(List<String> values) {
            addCriterion("course_author not in", values, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorBetween(String value1, String value2) {
            addCriterion("course_author between", value1, value2, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseAuthorNotBetween(String value1, String value2) {
            addCriterion("course_author not between", value1, value2, "courseAuthor");
            return (Criteria) this;
        }

        public Criteria andCourseCoverIsNull() {
            addCriterion("course_cover is null");
            return (Criteria) this;
        }

        public Criteria andCourseCoverIsNotNull() {
            addCriterion("course_cover is not null");
            return (Criteria) this;
        }

        public Criteria andCourseCoverEqualTo(String value) {
            addCriterion("course_cover =", value, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverNotEqualTo(String value) {
            addCriterion("course_cover <>", value, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverGreaterThan(String value) {
            addCriterion("course_cover >", value, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverGreaterThanOrEqualTo(String value) {
            addCriterion("course_cover >=", value, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverLessThan(String value) {
            addCriterion("course_cover <", value, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverLessThanOrEqualTo(String value) {
            addCriterion("course_cover <=", value, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverLike(String value) {
            addCriterion("course_cover like", value, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverNotLike(String value) {
            addCriterion("course_cover not like", value, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverIn(List<String> values) {
            addCriterion("course_cover in", values, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverNotIn(List<String> values) {
            addCriterion("course_cover not in", values, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverBetween(String value1, String value2) {
            addCriterion("course_cover between", value1, value2, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseCoverNotBetween(String value1, String value2) {
            addCriterion("course_cover not between", value1, value2, "courseCover");
            return (Criteria) this;
        }

        public Criteria andCourseTimeIsNull() {
            addCriterion("course_time is null");
            return (Criteria) this;
        }

        public Criteria andCourseTimeIsNotNull() {
            addCriterion("course_time is not null");
            return (Criteria) this;
        }

        public Criteria andCourseTimeEqualTo(String value) {
            addCriterion("course_time =", value, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeNotEqualTo(String value) {
            addCriterion("course_time <>", value, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeGreaterThan(String value) {
            addCriterion("course_time >", value, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeGreaterThanOrEqualTo(String value) {
            addCriterion("course_time >=", value, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeLessThan(String value) {
            addCriterion("course_time <", value, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeLessThanOrEqualTo(String value) {
            addCriterion("course_time <=", value, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeLike(String value) {
            addCriterion("course_time like", value, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeNotLike(String value) {
            addCriterion("course_time not like", value, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeIn(List<String> values) {
            addCriterion("course_time in", values, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeNotIn(List<String> values) {
            addCriterion("course_time not in", values, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeBetween(String value1, String value2) {
            addCriterion("course_time between", value1, value2, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseTimeNotBetween(String value1, String value2) {
            addCriterion("course_time not between", value1, value2, "courseTime");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIsNull() {
            addCriterion("course_status is null");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIsNotNull() {
            addCriterion("course_status is not null");
            return (Criteria) this;
        }

        public Criteria andCourseStatusEqualTo(Boolean value) {
            addCriterion("course_status =", value, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCourseStatusNotEqualTo(Boolean value) {
            addCriterion("course_status <>", value, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCourseStatusGreaterThan(Boolean value) {
            addCriterion("course_status >", value, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCourseStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("course_status >=", value, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCourseStatusLessThan(Boolean value) {
            addCriterion("course_status <", value, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCourseStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("course_status <=", value, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCourseStatusIn(List<Boolean> values) {
            addCriterion("course_status in", values, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCourseStatusNotIn(List<Boolean> values) {
            addCriterion("course_status not in", values, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCourseStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("course_status between", value1, value2, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCourseStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("course_status not between", value1, value2, "courseStatus");
            return (Criteria) this;
        }

        public Criteria andCoursePriceIsNull() {
            addCriterion("course_price is null");
            return (Criteria) this;
        }

        public Criteria andCoursePriceIsNotNull() {
            addCriterion("course_price is not null");
            return (Criteria) this;
        }

        public Criteria andCoursePriceEqualTo(BigDecimal value) {
            addCriterion("course_price =", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceNotEqualTo(BigDecimal value) {
            addCriterion("course_price <>", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceGreaterThan(BigDecimal value) {
            addCriterion("course_price >", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("course_price >=", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceLessThan(BigDecimal value) {
            addCriterion("course_price <", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("course_price <=", value, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceIn(List<BigDecimal> values) {
            addCriterion("course_price in", values, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceNotIn(List<BigDecimal> values) {
            addCriterion("course_price not in", values, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("course_price between", value1, value2, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCoursePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("course_price not between", value1, value2, "coursePrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceIsNull() {
            addCriterion("course_discount_price is null");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceIsNotNull() {
            addCriterion("course_discount_price is not null");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceEqualTo(BigDecimal value) {
            addCriterion("course_discount_price =", value, "courseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceNotEqualTo(BigDecimal value) {
            addCriterion("course_discount_price <>", value, "courseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceGreaterThan(BigDecimal value) {
            addCriterion("course_discount_price >", value, "courseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("course_discount_price >=", value, "courseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceLessThan(BigDecimal value) {
            addCriterion("course_discount_price <", value, "courseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("course_discount_price <=", value, "courseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceIn(List<BigDecimal> values) {
            addCriterion("course_discount_price in", values, "courseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceNotIn(List<BigDecimal> values) {
            addCriterion("course_discount_price not in", values, "courseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("course_discount_price between", value1, value2, "courseDiscountPrice");
            return (Criteria) this;
        }

        public Criteria andCourseDiscountPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("course_discount_price not between", value1, value2, "courseDiscountPrice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_courses
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 26 15:02:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_courses
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}