package com.mark.manager.pojo;

import java.io.Serializable;

public class VproComment implements Serializable {
    @Override
    public String toString() {
        return "VproComment{" +
                "vproCommentId=" + vproCommentId +
                ", vproCommentContent='" + vproCommentContent + '\'' +
                ", vproCommentUserId=" + vproCommentUserId +
                ", vproCommentCourseId=" + vproCommentCourseId +
                ", vproCommentLessonId=" + vproCommentLessonId +
                ", vproCommentReplyId=" + vproCommentReplyId +
                ", vproCommentReplyMainId=" + vproCommentReplyMainId +
                ", vproCommentIsPublished=" + vproCommentIsPublished +
                ", vproCommentTime='" + vproCommentTime + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment.vpro_comment_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer vproCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment.vpro_comment_content
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private String vproCommentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment.vpro_comment_user_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer vproCommentUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment.vpro_comment_course_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer vproCommentCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment.vpro_comment_lesson_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer vproCommentLessonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment.vpro_comment_reply_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer vproCommentReplyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment.vpro_comment_reply_main_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer vproCommentReplyMainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment.vpro_comment_is_published
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Boolean vproCommentIsPublished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment.vpro_comment_time
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private String vproCommentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment.vpro_comment_id
     *
     * @return the value of vpro_comment.vpro_comment_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getVproCommentId() {
        return vproCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment.vpro_comment_id
     *
     * @param vproCommentId the value for vpro_comment.vpro_comment_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setVproCommentId(Integer vproCommentId) {
        this.vproCommentId = vproCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment.vpro_comment_content
     *
     * @return the value of vpro_comment.vpro_comment_content
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public String getVproCommentContent() {
        return vproCommentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment.vpro_comment_content
     *
     * @param vproCommentContent the value for vpro_comment.vpro_comment_content
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setVproCommentContent(String vproCommentContent) {
        this.vproCommentContent = vproCommentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment.vpro_comment_user_id
     *
     * @return the value of vpro_comment.vpro_comment_user_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getVproCommentUserId() {
        return vproCommentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment.vpro_comment_user_id
     *
     * @param vproCommentUserId the value for vpro_comment.vpro_comment_user_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setVproCommentUserId(Integer vproCommentUserId) {
        this.vproCommentUserId = vproCommentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment.vpro_comment_course_id
     *
     * @return the value of vpro_comment.vpro_comment_course_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getVproCommentCourseId() {
        return vproCommentCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment.vpro_comment_course_id
     *
     * @param vproCommentCourseId the value for vpro_comment.vpro_comment_course_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setVproCommentCourseId(Integer vproCommentCourseId) {
        this.vproCommentCourseId = vproCommentCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment.vpro_comment_lesson_id
     *
     * @return the value of vpro_comment.vpro_comment_lesson_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getVproCommentLessonId() {
        return vproCommentLessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment.vpro_comment_lesson_id
     *
     * @param vproCommentLessonId the value for vpro_comment.vpro_comment_lesson_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setVproCommentLessonId(Integer vproCommentLessonId) {
        this.vproCommentLessonId = vproCommentLessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment.vpro_comment_reply_id
     *
     * @return the value of vpro_comment.vpro_comment_reply_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getVproCommentReplyId() {
        return vproCommentReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment.vpro_comment_reply_id
     *
     * @param vproCommentReplyId the value for vpro_comment.vpro_comment_reply_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setVproCommentReplyId(Integer vproCommentReplyId) {
        this.vproCommentReplyId = vproCommentReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment.vpro_comment_reply_main_id
     *
     * @return the value of vpro_comment.vpro_comment_reply_main_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getVproCommentReplyMainId() {
        return vproCommentReplyMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment.vpro_comment_reply_main_id
     *
     * @param vproCommentReplyMainId the value for vpro_comment.vpro_comment_reply_main_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setVproCommentReplyMainId(Integer vproCommentReplyMainId) {
        this.vproCommentReplyMainId = vproCommentReplyMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment.vpro_comment_is_published
     *
     * @return the value of vpro_comment.vpro_comment_is_published
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Boolean getVproCommentIsPublished() {
        return vproCommentIsPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment.vpro_comment_is_published
     *
     * @param vproCommentIsPublished the value for vpro_comment.vpro_comment_is_published
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setVproCommentIsPublished(Boolean vproCommentIsPublished) {
        this.vproCommentIsPublished = vproCommentIsPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment.vpro_comment_time
     *
     * @return the value of vpro_comment.vpro_comment_time
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public String getVproCommentTime() {
        return vproCommentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment.vpro_comment_time
     *
     * @param vproCommentTime the value for vpro_comment.vpro_comment_time
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setVproCommentTime(String vproCommentTime) {
        this.vproCommentTime = vproCommentTime;
    }
}