package com.mark.manager.pojo;

public class VproVideoFiles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video_files.video_file_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Integer videoFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video_files.video_file_key
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private String videoFileKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video_files.video_file_uptime
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private String videoFileUptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video_files.video_file_isuploaded
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Byte videoFileIsuploaded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video_files.video_file_isused
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Byte videoFileIsused;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video_files.video_file_size
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Integer videoFileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video_files.video_file_lesson_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Integer videoFileLessonId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video_files.video_file_id
     *
     * @return the value of vpro_video_files.video_file_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Integer getVideoFileId() {
        return videoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video_files.video_file_id
     *
     * @param videoFileId the value for vpro_video_files.video_file_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoFileId(Integer videoFileId) {
        this.videoFileId = videoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video_files.video_file_key
     *
     * @return the value of vpro_video_files.video_file_key
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public String getVideoFileKey() {
        return videoFileKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video_files.video_file_key
     *
     * @param videoFileKey the value for vpro_video_files.video_file_key
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoFileKey(String videoFileKey) {
        this.videoFileKey = videoFileKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video_files.video_file_uptime
     *
     * @return the value of vpro_video_files.video_file_uptime
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public String getVideoFileUptime() {
        return videoFileUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video_files.video_file_uptime
     *
     * @param videoFileUptime the value for vpro_video_files.video_file_uptime
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoFileUptime(String videoFileUptime) {
        this.videoFileUptime = videoFileUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video_files.video_file_isuploaded
     *
     * @return the value of vpro_video_files.video_file_isuploaded
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Byte getVideoFileIsuploaded() {
        return videoFileIsuploaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video_files.video_file_isuploaded
     *
     * @param videoFileIsuploaded the value for vpro_video_files.video_file_isuploaded
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoFileIsuploaded(Byte videoFileIsuploaded) {
        this.videoFileIsuploaded = videoFileIsuploaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video_files.video_file_isused
     *
     * @return the value of vpro_video_files.video_file_isused
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Byte getVideoFileIsused() {
        return videoFileIsused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video_files.video_file_isused
     *
     * @param videoFileIsused the value for vpro_video_files.video_file_isused
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoFileIsused(Byte videoFileIsused) {
        this.videoFileIsused = videoFileIsused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video_files.video_file_size
     *
     * @return the value of vpro_video_files.video_file_size
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Integer getVideoFileSize() {
        return videoFileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video_files.video_file_size
     *
     * @param videoFileSize the value for vpro_video_files.video_file_size
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoFileSize(Integer videoFileSize) {
        this.videoFileSize = videoFileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video_files.video_file_lesson_id
     *
     * @return the value of vpro_video_files.video_file_lesson_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Integer getVideoFileLessonId() {
        return videoFileLessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video_files.video_file_lesson_id
     *
     * @param videoFileLessonId the value for vpro_video_files.video_file_lesson_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoFileLessonId(Integer videoFileLessonId) {
        this.videoFileLessonId = videoFileLessonId;
    }
}