package com.mark.manager.pojo;

public class VproVideo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video.video_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video.video_file_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private String videoFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video.video_author
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private String videoAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video.video_tag
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private String videoTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video.video_detail_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Integer videoDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video.video_lesson_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Integer videoLessonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_video.video_lesson_isused
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Boolean videoLessonIsused;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video.video_id
     *
     * @return the value of vpro_video.video_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video.video_id
     *
     * @param videoId the value for vpro_video.video_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video.video_file_id
     *
     * @return the value of vpro_video.video_file_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public String getVideoFileId() {
        return videoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video.video_file_id
     *
     * @param videoFileId the value for vpro_video.video_file_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoFileId(String videoFileId) {
        this.videoFileId = videoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video.video_author
     *
     * @return the value of vpro_video.video_author
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public String getVideoAuthor() {
        return videoAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video.video_author
     *
     * @param videoAuthor the value for vpro_video.video_author
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoAuthor(String videoAuthor) {
        this.videoAuthor = videoAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video.video_tag
     *
     * @return the value of vpro_video.video_tag
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public String getVideoTag() {
        return videoTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video.video_tag
     *
     * @param videoTag the value for vpro_video.video_tag
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoTag(String videoTag) {
        this.videoTag = videoTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video.video_detail_id
     *
     * @return the value of vpro_video.video_detail_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Integer getVideoDetailId() {
        return videoDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video.video_detail_id
     *
     * @param videoDetailId the value for vpro_video.video_detail_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoDetailId(Integer videoDetailId) {
        this.videoDetailId = videoDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video.video_lesson_id
     *
     * @return the value of vpro_video.video_lesson_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Integer getVideoLessonId() {
        return videoLessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video.video_lesson_id
     *
     * @param videoLessonId the value for vpro_video.video_lesson_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoLessonId(Integer videoLessonId) {
        this.videoLessonId = videoLessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_video.video_lesson_isused
     *
     * @return the value of vpro_video.video_lesson_isused
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Boolean getVideoLessonIsused() {
        return videoLessonIsused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_video.video_lesson_isused
     *
     * @param videoLessonIsused the value for vpro_video.video_lesson_isused
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setVideoLessonIsused(Boolean videoLessonIsused) {
        this.videoLessonIsused = videoLessonIsused;
    }
}