package com.mark.manager.pojo;

public class VproCoursesContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_content.detail_id
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    private Integer detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_content.course_id
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_content.course_content
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    private String courseContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_content.detail_id
     *
     * @return the value of vpro_courses_content.detail_id
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_content.detail_id
     *
     * @param detailId the value for vpro_courses_content.detail_id
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_content.course_id
     *
     * @return the value of vpro_courses_content.course_id
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_content.course_id
     *
     * @param courseId the value for vpro_courses_content.course_id
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_content.course_content
     *
     * @return the value of vpro_courses_content.course_content
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public String getCourseContent() {
        return courseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_content.course_content
     *
     * @param courseContent the value for vpro_courses_content.course_content
     *
     * @mbg.generated Fri Oct 26 15:02:11 CST 2018
     */
    public void setCourseContent(String courseContent) {
        this.courseContent = courseContent;
    }
}