package com.mark.manager.pojo;

public class VproCart {
    @Override
    public String toString() {
        return "VproCart{" +
                "cartId=" + cartId +
                ", cartAddtime='" + cartAddtime + '\'' +
                ", cartUserid=" + cartUserid +
                ", cartPayment='" + cartPayment + '\'' +
                ", cartStatus='" + cartStatus + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart.cart_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Long cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart.cart_addtime
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private String cartAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart.cart_userid
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer cartUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart.cart_payment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private String cartPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart.cart_status
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private String cartStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart.cart_id
     *
     * @return the value of vpro_cart.cart_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Long getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart.cart_id
     *
     * @param cartId the value for vpro_cart.cart_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart.cart_addtime
     *
     * @return the value of vpro_cart.cart_addtime
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public String getCartAddtime() {
        return cartAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart.cart_addtime
     *
     * @param cartAddtime the value for vpro_cart.cart_addtime
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartAddtime(String cartAddtime) {
        this.cartAddtime = cartAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart.cart_userid
     *
     * @return the value of vpro_cart.cart_userid
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getCartUserid() {
        return cartUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart.cart_userid
     *
     * @param cartUserid the value for vpro_cart.cart_userid
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartUserid(Integer cartUserid) {
        this.cartUserid = cartUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart.cart_payment
     *
     * @return the value of vpro_cart.cart_payment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public String getCartPayment() {
        return cartPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart.cart_payment
     *
     * @param cartPayment the value for vpro_cart.cart_payment
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartPayment(String cartPayment) {
        this.cartPayment = cartPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart.cart_status
     *
     * @return the value of vpro_cart.cart_status
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public String getCartStatus() {
        return cartStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart.cart_status
     *
     * @param cartStatus the value for vpro_cart.cart_status
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartStatus(String cartStatus) {
        this.cartStatus = cartStatus;
    }
}