package com.mark.manager.pojo;

import java.util.ArrayList;
import java.util.List;

public class VproCartDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public VproCartDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCartDetailIdIsNull() {
            addCriterion("cart_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdIsNotNull() {
            addCriterion("cart_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdEqualTo(Integer value) {
            addCriterion("cart_detail_id =", value, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdNotEqualTo(Integer value) {
            addCriterion("cart_detail_id <>", value, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdGreaterThan(Integer value) {
            addCriterion("cart_detail_id >", value, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cart_detail_id >=", value, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdLessThan(Integer value) {
            addCriterion("cart_detail_id <", value, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdLessThanOrEqualTo(Integer value) {
            addCriterion("cart_detail_id <=", value, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdIn(List<Integer> values) {
            addCriterion("cart_detail_id in", values, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdNotIn(List<Integer> values) {
            addCriterion("cart_detail_id not in", values, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdBetween(Integer value1, Integer value2) {
            addCriterion("cart_detail_id between", value1, value2, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartDetailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cart_detail_id not between", value1, value2, "cartDetailId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdIsNull() {
            addCriterion("cart_course_id is null");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdIsNotNull() {
            addCriterion("cart_course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdEqualTo(String value) {
            addCriterion("cart_course_id =", value, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdNotEqualTo(String value) {
            addCriterion("cart_course_id <>", value, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdGreaterThan(String value) {
            addCriterion("cart_course_id >", value, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdGreaterThanOrEqualTo(String value) {
            addCriterion("cart_course_id >=", value, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdLessThan(String value) {
            addCriterion("cart_course_id <", value, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdLessThanOrEqualTo(String value) {
            addCriterion("cart_course_id <=", value, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdLike(String value) {
            addCriterion("cart_course_id like", value, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdNotLike(String value) {
            addCriterion("cart_course_id not like", value, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdIn(List<String> values) {
            addCriterion("cart_course_id in", values, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdNotIn(List<String> values) {
            addCriterion("cart_course_id not in", values, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdBetween(String value1, String value2) {
            addCriterion("cart_course_id between", value1, value2, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartCourseIdNotBetween(String value1, String value2) {
            addCriterion("cart_course_id not between", value1, value2, "cartCourseId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdIsNull() {
            addCriterion("cart_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andCartParentIdIsNotNull() {
            addCriterion("cart_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andCartParentIdEqualTo(Long value) {
            addCriterion("cart_parent_id =", value, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdNotEqualTo(Long value) {
            addCriterion("cart_parent_id <>", value, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdGreaterThan(Long value) {
            addCriterion("cart_parent_id >", value, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("cart_parent_id >=", value, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdLessThan(Long value) {
            addCriterion("cart_parent_id <", value, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdLessThanOrEqualTo(Long value) {
            addCriterion("cart_parent_id <=", value, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdIn(List<Long> values) {
            addCriterion("cart_parent_id in", values, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdNotIn(List<Long> values) {
            addCriterion("cart_parent_id not in", values, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdBetween(Long value1, Long value2) {
            addCriterion("cart_parent_id between", value1, value2, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartParentIdNotBetween(Long value1, Long value2) {
            addCriterion("cart_parent_id not between", value1, value2, "cartParentId");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeIsNull() {
            addCriterion("cart_add_time is null");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeIsNotNull() {
            addCriterion("cart_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeEqualTo(String value) {
            addCriterion("cart_add_time =", value, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeNotEqualTo(String value) {
            addCriterion("cart_add_time <>", value, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeGreaterThan(String value) {
            addCriterion("cart_add_time >", value, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeGreaterThanOrEqualTo(String value) {
            addCriterion("cart_add_time >=", value, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeLessThan(String value) {
            addCriterion("cart_add_time <", value, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeLessThanOrEqualTo(String value) {
            addCriterion("cart_add_time <=", value, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeLike(String value) {
            addCriterion("cart_add_time like", value, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeNotLike(String value) {
            addCriterion("cart_add_time not like", value, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeIn(List<String> values) {
            addCriterion("cart_add_time in", values, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeNotIn(List<String> values) {
            addCriterion("cart_add_time not in", values, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeBetween(String value1, String value2) {
            addCriterion("cart_add_time between", value1, value2, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartAddTimeNotBetween(String value1, String value2) {
            addCriterion("cart_add_time not between", value1, value2, "cartAddTime");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieIsNull() {
            addCriterion("cart_is_cookie is null");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieIsNotNull() {
            addCriterion("cart_is_cookie is not null");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieEqualTo(Boolean value) {
            addCriterion("cart_is_cookie =", value, "cartIsCookie");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieNotEqualTo(Boolean value) {
            addCriterion("cart_is_cookie <>", value, "cartIsCookie");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieGreaterThan(Boolean value) {
            addCriterion("cart_is_cookie >", value, "cartIsCookie");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieGreaterThanOrEqualTo(Boolean value) {
            addCriterion("cart_is_cookie >=", value, "cartIsCookie");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieLessThan(Boolean value) {
            addCriterion("cart_is_cookie <", value, "cartIsCookie");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieLessThanOrEqualTo(Boolean value) {
            addCriterion("cart_is_cookie <=", value, "cartIsCookie");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieIn(List<Boolean> values) {
            addCriterion("cart_is_cookie in", values, "cartIsCookie");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieNotIn(List<Boolean> values) {
            addCriterion("cart_is_cookie not in", values, "cartIsCookie");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieBetween(Boolean value1, Boolean value2) {
            addCriterion("cart_is_cookie between", value1, value2, "cartIsCookie");
            return (Criteria) this;
        }

        public Criteria andCartIsCookieNotBetween(Boolean value1, Boolean value2) {
            addCriterion("cart_is_cookie not between", value1, value2, "cartIsCookie");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 21 13:25:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_cart_detail
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}