package com.mark.manager.pojo;

public class VproRolesPermissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_roles_permissions.roles_permissions_id
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    private Integer rolesPermissionsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_roles_permissions.roles_id
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    private Integer rolesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_roles_permissions.permissions_id
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    private Integer permissionsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_roles_permissions.roles_permissions_id
     *
     * @return the value of vpro_roles_permissions.roles_permissions_id
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    public Integer getRolesPermissionsId() {
        return rolesPermissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_roles_permissions.roles_permissions_id
     *
     * @param rolesPermissionsId the value for vpro_roles_permissions.roles_permissions_id
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    public void setRolesPermissionsId(Integer rolesPermissionsId) {
        this.rolesPermissionsId = rolesPermissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_roles_permissions.roles_id
     *
     * @return the value of vpro_roles_permissions.roles_id
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    public Integer getRolesId() {
        return rolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_roles_permissions.roles_id
     *
     * @param rolesId the value for vpro_roles_permissions.roles_id
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    public void setRolesId(Integer rolesId) {
        this.rolesId = rolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_roles_permissions.permissions_id
     *
     * @return the value of vpro_roles_permissions.permissions_id
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    public Integer getPermissionsId() {
        return permissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_roles_permissions.permissions_id
     *
     * @param permissionsId the value for vpro_roles_permissions.permissions_id
     *
     * @mbg.generated Wed Oct 17 23:12:35 CST 2018
     */
    public void setPermissionsId(Integer permissionsId) {
        this.permissionsId = permissionsId;
    }
}