package com.mark.manager.pojo;

public class VproCartDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart_detail.cart_detail_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer cartDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart_detail.cart_course_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private String cartCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart_detail.cart_parent_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Long cartParentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart_detail.cart_detail_id
     *
     * @return the value of vpro_cart_detail.cart_detail_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getCartDetailId() {
        return cartDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart_detail.cart_detail_id
     *
     * @param cartDetailId the value for vpro_cart_detail.cart_detail_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartDetailId(Integer cartDetailId) {
        this.cartDetailId = cartDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart_detail.cart_course_id
     *
     * @return the value of vpro_cart_detail.cart_course_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public String getCartCourseId() {
        return cartCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart_detail.cart_course_id
     *
     * @param cartCourseId the value for vpro_cart_detail.cart_course_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartCourseId(String cartCourseId) {
        this.cartCourseId = cartCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart_detail.cart_parent_id
     *
     * @return the value of vpro_cart_detail.cart_parent_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Long getCartParentId() {
        return cartParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart_detail.cart_parent_id
     *
     * @param cartParentId the value for vpro_cart_detail.cart_parent_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartParentId(Long cartParentId) {
        this.cartParentId = cartParentId;
    }
}