package com.mark.manager.pojo;

public class VproCartDetail extends VproCartDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart_detail.cart_add_time
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private String cartAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_cart_detail.cart_is_cookie
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Boolean cartIsCookie;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart_detail.cart_add_time
     *
     * @return the value of vpro_cart_detail.cart_add_time
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public String getCartAddTime() {
        return cartAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart_detail.cart_add_time
     *
     * @param cartAddTime the value for vpro_cart_detail.cart_add_time
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartAddTime(String cartAddTime) {
        this.cartAddTime = cartAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_cart_detail.cart_is_cookie
     *
     * @return the value of vpro_cart_detail.cart_is_cookie
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Boolean getCartIsCookie() {
        return cartIsCookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_cart_detail.cart_is_cookie
     *
     * @param cartIsCookie the value for vpro_cart_detail.cart_is_cookie
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCartIsCookie(Boolean cartIsCookie) {
        this.cartIsCookie = cartIsCookie;
    }
}