package com.mark.manager.pojo;

public class VproCommentSupportRate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment_support_rate.comment_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment_support_rate.commit_agree
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer commitAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment_support_rate.comment_oppose
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    private Integer commentOppose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment_support_rate.comment_id
     *
     * @return the value of vpro_comment_support_rate.comment_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment_support_rate.comment_id
     *
     * @param commentId the value for vpro_comment_support_rate.comment_id
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment_support_rate.commit_agree
     *
     * @return the value of vpro_comment_support_rate.commit_agree
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getCommitAgree() {
        return commitAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment_support_rate.commit_agree
     *
     * @param commitAgree the value for vpro_comment_support_rate.commit_agree
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCommitAgree(Integer commitAgree) {
        this.commitAgree = commitAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment_support_rate.comment_oppose
     *
     * @return the value of vpro_comment_support_rate.comment_oppose
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public Integer getCommentOppose() {
        return commentOppose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment_support_rate.comment_oppose
     *
     * @param commentOppose the value for vpro_comment_support_rate.comment_oppose
     *
     * @mbg.generated Thu Feb 21 13:25:44 CST 2019
     */
    public void setCommentOppose(Integer commentOppose) {
        this.commentOppose = commentOppose;
    }
}