package com.mark.manager.pojo;

public class VproCoursesImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_image.image_id
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    private Integer imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_image.image_url
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_image.image_author
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    private Integer imageAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_image.image_used_location
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    private String imageUsedLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_image.image_id
     *
     * @return the value of vpro_courses_image.image_id
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_image.image_id
     *
     * @param imageId the value for vpro_courses_image.image_id
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_image.image_url
     *
     * @return the value of vpro_courses_image.image_url
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_image.image_url
     *
     * @param imageUrl the value for vpro_courses_image.image_url
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_image.image_author
     *
     * @return the value of vpro_courses_image.image_author
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    public Integer getImageAuthor() {
        return imageAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_image.image_author
     *
     * @param imageAuthor the value for vpro_courses_image.image_author
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    public void setImageAuthor(Integer imageAuthor) {
        this.imageAuthor = imageAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_image.image_used_location
     *
     * @return the value of vpro_courses_image.image_used_location
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    public String getImageUsedLocation() {
        return imageUsedLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_image.image_used_location
     *
     * @param imageUsedLocation the value for vpro_courses_image.image_used_location
     *
     * @mbg.generated Sun Jan 13 11:45:07 CST 2019
     */
    public void setImageUsedLocation(String imageUsedLocation) {
        this.imageUsedLocation = imageUsedLocation;
    }
}