package com.mark.manager.pojo;

public class VproOrderLogs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_logs.log_id
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_logs.log_operation
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    private String logOperation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_logs.log_time
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    private String logTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_logs.user_id
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_logs.order_id
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_order_logs.log_message
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    private String logMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_logs.log_id
     *
     * @return the value of vpro_order_logs.log_id
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_logs.log_id
     *
     * @param logId the value for vpro_order_logs.log_id
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_logs.log_operation
     *
     * @return the value of vpro_order_logs.log_operation
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public String getLogOperation() {
        return logOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_logs.log_operation
     *
     * @param logOperation the value for vpro_order_logs.log_operation
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public void setLogOperation(String logOperation) {
        this.logOperation = logOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_logs.log_time
     *
     * @return the value of vpro_order_logs.log_time
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public String getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_logs.log_time
     *
     * @param logTime the value for vpro_order_logs.log_time
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public void setLogTime(String logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_logs.user_id
     *
     * @return the value of vpro_order_logs.user_id
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_logs.user_id
     *
     * @param userId the value for vpro_order_logs.user_id
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_logs.order_id
     *
     * @return the value of vpro_order_logs.order_id
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_logs.order_id
     *
     * @param orderId the value for vpro_order_logs.order_id
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_order_logs.log_message
     *
     * @return the value of vpro_order_logs.log_message
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public String getLogMessage() {
        return logMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_order_logs.log_message
     *
     * @param logMessage the value for vpro_order_logs.log_message
     *
     * @mbg.generated Wed Feb 27 17:28:28 CST 2019
     */
    public void setLogMessage(String logMessage) {
        this.logMessage = logMessage;
    }
}