package com.mark.manager.pojo;

import java.io.Serializable;

public class VproCoursesContent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_content.detail_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Integer detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_content.course_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_content.course_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    private String courseContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_content.detail_id
     *
     * @return the value of vpro_courses_content.detail_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_content.detail_id
     *
     * @param detailId the value for vpro_courses_content.detail_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_content.course_id
     *
     * @return the value of vpro_courses_content.course_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_content.course_id
     *
     * @param courseId the value for vpro_courses_content.course_id
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_content.course_content
     *
     * @return the value of vpro_courses_content.course_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public String getCourseContent() {
        return courseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_content.course_content
     *
     * @param courseContent the value for vpro_courses_content.course_content
     *
     * @mbg.generated Sat Dec 01 12:09:12 CST 2018
     */
    public void setCourseContent(String courseContent) {
        this.courseContent = courseContent;
    }

    @Override
    public String toString() {
        return "VproCoursesContent{" +
                "detailId=" + detailId +
                ", courseId=" + courseId +
                ", courseContent='" + courseContent + '\'' +
                '}';
    }
}