package com.mark.manager.pojo;

import java.util.ArrayList;
import java.util.List;

public class VproVideoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public VproVideoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVideoIdIsNull() {
            addCriterion("video_id is null");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNotNull() {
            addCriterion("video_id is not null");
            return (Criteria) this;
        }

        public Criteria andVideoIdEqualTo(Integer value) {
            addCriterion("video_id =", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotEqualTo(Integer value) {
            addCriterion("video_id <>", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThan(Integer value) {
            addCriterion("video_id >", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("video_id >=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThan(Integer value) {
            addCriterion("video_id <", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThanOrEqualTo(Integer value) {
            addCriterion("video_id <=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdIn(List<Integer> values) {
            addCriterion("video_id in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotIn(List<Integer> values) {
            addCriterion("video_id not in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdBetween(Integer value1, Integer value2) {
            addCriterion("video_id between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("video_id not between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdIsNull() {
            addCriterion("video_file_id is null");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdIsNotNull() {
            addCriterion("video_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdEqualTo(String value) {
            addCriterion("video_file_id =", value, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdNotEqualTo(String value) {
            addCriterion("video_file_id <>", value, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdGreaterThan(String value) {
            addCriterion("video_file_id >", value, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdGreaterThanOrEqualTo(String value) {
            addCriterion("video_file_id >=", value, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdLessThan(String value) {
            addCriterion("video_file_id <", value, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdLessThanOrEqualTo(String value) {
            addCriterion("video_file_id <=", value, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdLike(String value) {
            addCriterion("video_file_id like", value, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdNotLike(String value) {
            addCriterion("video_file_id not like", value, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdIn(List<String> values) {
            addCriterion("video_file_id in", values, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdNotIn(List<String> values) {
            addCriterion("video_file_id not in", values, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdBetween(String value1, String value2) {
            addCriterion("video_file_id between", value1, value2, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoFileIdNotBetween(String value1, String value2) {
            addCriterion("video_file_id not between", value1, value2, "videoFileId");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorIsNull() {
            addCriterion("video_author is null");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorIsNotNull() {
            addCriterion("video_author is not null");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorEqualTo(String value) {
            addCriterion("video_author =", value, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorNotEqualTo(String value) {
            addCriterion("video_author <>", value, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorGreaterThan(String value) {
            addCriterion("video_author >", value, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("video_author >=", value, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorLessThan(String value) {
            addCriterion("video_author <", value, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorLessThanOrEqualTo(String value) {
            addCriterion("video_author <=", value, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorLike(String value) {
            addCriterion("video_author like", value, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorNotLike(String value) {
            addCriterion("video_author not like", value, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorIn(List<String> values) {
            addCriterion("video_author in", values, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorNotIn(List<String> values) {
            addCriterion("video_author not in", values, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorBetween(String value1, String value2) {
            addCriterion("video_author between", value1, value2, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoAuthorNotBetween(String value1, String value2) {
            addCriterion("video_author not between", value1, value2, "videoAuthor");
            return (Criteria) this;
        }

        public Criteria andVideoTagIsNull() {
            addCriterion("video_tag is null");
            return (Criteria) this;
        }

        public Criteria andVideoTagIsNotNull() {
            addCriterion("video_tag is not null");
            return (Criteria) this;
        }

        public Criteria andVideoTagEqualTo(String value) {
            addCriterion("video_tag =", value, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagNotEqualTo(String value) {
            addCriterion("video_tag <>", value, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagGreaterThan(String value) {
            addCriterion("video_tag >", value, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagGreaterThanOrEqualTo(String value) {
            addCriterion("video_tag >=", value, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagLessThan(String value) {
            addCriterion("video_tag <", value, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagLessThanOrEqualTo(String value) {
            addCriterion("video_tag <=", value, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagLike(String value) {
            addCriterion("video_tag like", value, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagNotLike(String value) {
            addCriterion("video_tag not like", value, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagIn(List<String> values) {
            addCriterion("video_tag in", values, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagNotIn(List<String> values) {
            addCriterion("video_tag not in", values, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagBetween(String value1, String value2) {
            addCriterion("video_tag between", value1, value2, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoTagNotBetween(String value1, String value2) {
            addCriterion("video_tag not between", value1, value2, "videoTag");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdIsNull() {
            addCriterion("video_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdIsNotNull() {
            addCriterion("video_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdEqualTo(Integer value) {
            addCriterion("video_detail_id =", value, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdNotEqualTo(Integer value) {
            addCriterion("video_detail_id <>", value, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdGreaterThan(Integer value) {
            addCriterion("video_detail_id >", value, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("video_detail_id >=", value, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdLessThan(Integer value) {
            addCriterion("video_detail_id <", value, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdLessThanOrEqualTo(Integer value) {
            addCriterion("video_detail_id <=", value, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdIn(List<Integer> values) {
            addCriterion("video_detail_id in", values, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdNotIn(List<Integer> values) {
            addCriterion("video_detail_id not in", values, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdBetween(Integer value1, Integer value2) {
            addCriterion("video_detail_id between", value1, value2, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoDetailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("video_detail_id not between", value1, value2, "videoDetailId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdIsNull() {
            addCriterion("video_lesson_id is null");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdIsNotNull() {
            addCriterion("video_lesson_id is not null");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdEqualTo(Integer value) {
            addCriterion("video_lesson_id =", value, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdNotEqualTo(Integer value) {
            addCriterion("video_lesson_id <>", value, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdGreaterThan(Integer value) {
            addCriterion("video_lesson_id >", value, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("video_lesson_id >=", value, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdLessThan(Integer value) {
            addCriterion("video_lesson_id <", value, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdLessThanOrEqualTo(Integer value) {
            addCriterion("video_lesson_id <=", value, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdIn(List<Integer> values) {
            addCriterion("video_lesson_id in", values, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdNotIn(List<Integer> values) {
            addCriterion("video_lesson_id not in", values, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdBetween(Integer value1, Integer value2) {
            addCriterion("video_lesson_id between", value1, value2, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIdNotBetween(Integer value1, Integer value2) {
            addCriterion("video_lesson_id not between", value1, value2, "videoLessonId");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedIsNull() {
            addCriterion("video_lesson_isused is null");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedIsNotNull() {
            addCriterion("video_lesson_isused is not null");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedEqualTo(Boolean value) {
            addCriterion("video_lesson_isused =", value, "videoLessonIsused");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedNotEqualTo(Boolean value) {
            addCriterion("video_lesson_isused <>", value, "videoLessonIsused");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedGreaterThan(Boolean value) {
            addCriterion("video_lesson_isused >", value, "videoLessonIsused");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("video_lesson_isused >=", value, "videoLessonIsused");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedLessThan(Boolean value) {
            addCriterion("video_lesson_isused <", value, "videoLessonIsused");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedLessThanOrEqualTo(Boolean value) {
            addCriterion("video_lesson_isused <=", value, "videoLessonIsused");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedIn(List<Boolean> values) {
            addCriterion("video_lesson_isused in", values, "videoLessonIsused");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedNotIn(List<Boolean> values) {
            addCriterion("video_lesson_isused not in", values, "videoLessonIsused");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedBetween(Boolean value1, Boolean value2) {
            addCriterion("video_lesson_isused between", value1, value2, "videoLessonIsused");
            return (Criteria) this;
        }

        public Criteria andVideoLessonIsusedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("video_lesson_isused not between", value1, value2, "videoLessonIsused");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_video
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 27 17:05:37 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_video
     *
     * @mbg.generated Tue Nov 27 17:05:37 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}