package com.mark.manager.pojo;

public class VproPermissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_permissions.permissions_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private Integer permissionsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_permissions.permissions_name
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private String permissionsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_permissions.permissions_pid
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private Integer permissionsPid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_permissions.permissions_id
     *
     * @return the value of vpro_permissions.permissions_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public Integer getPermissionsId() {
        return permissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_permissions.permissions_id
     *
     * @param permissionsId the value for vpro_permissions.permissions_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setPermissionsId(Integer permissionsId) {
        this.permissionsId = permissionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_permissions.permissions_name
     *
     * @return the value of vpro_permissions.permissions_name
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public String getPermissionsName() {
        return permissionsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_permissions.permissions_name
     *
     * @param permissionsName the value for vpro_permissions.permissions_name
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setPermissionsName(String permissionsName) {
        this.permissionsName = permissionsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_permissions.permissions_pid
     *
     * @return the value of vpro_permissions.permissions_pid
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public Integer getPermissionsPid() {
        return permissionsPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_permissions.permissions_pid
     *
     * @param permissionsPid the value for vpro_permissions.permissions_pid
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setPermissionsPid(Integer permissionsPid) {
        this.permissionsPid = permissionsPid;
    }
}