package com.mark.manager.pojo;

public class VproRoles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_roles.roles_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private Integer rolesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_roles.roles_name
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private String rolesName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_roles.roles_id
     *
     * @return the value of vpro_roles.roles_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public Integer getRolesId() {
        return rolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_roles.roles_id
     *
     * @param rolesId the value for vpro_roles.roles_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setRolesId(Integer rolesId) {
        this.rolesId = rolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_roles.roles_name
     *
     * @return the value of vpro_roles.roles_name
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public String getRolesName() {
        return rolesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_roles.roles_name
     *
     * @param rolesName the value for vpro_roles.roles_name
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setRolesName(String rolesName) {
        this.rolesName = rolesName;
    }
}