package com.mark.manager.pojo;

import java.math.BigDecimal;

public class VproCourses {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses.course_id
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses.course_title
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    private String courseTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses.course_pid
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    private Integer coursePid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses.course_author
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    private String courseAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses.course_cover
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    private String courseCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses.course_time
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    private String courseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses.course_status
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    private Boolean courseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses.course_price
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    private BigDecimal coursePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses.course_discount_price
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    private BigDecimal courseDiscountPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses.course_id
     *
     * @return the value of vpro_courses.course_id
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses.course_id
     *
     * @param courseId the value for vpro_courses.course_id
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses.course_title
     *
     * @return the value of vpro_courses.course_title
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public String getCourseTitle() {
        return courseTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses.course_title
     *
     * @param courseTitle the value for vpro_courses.course_title
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public void setCourseTitle(String courseTitle) {
        this.courseTitle = courseTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses.course_pid
     *
     * @return the value of vpro_courses.course_pid
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public Integer getCoursePid() {
        return coursePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses.course_pid
     *
     * @param coursePid the value for vpro_courses.course_pid
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public void setCoursePid(Integer coursePid) {
        this.coursePid = coursePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses.course_author
     *
     * @return the value of vpro_courses.course_author
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public String getCourseAuthor() {
        return courseAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses.course_author
     *
     * @param courseAuthor the value for vpro_courses.course_author
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public void setCourseAuthor(String courseAuthor) {
        this.courseAuthor = courseAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses.course_cover
     *
     * @return the value of vpro_courses.course_cover
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public String getCourseCover() {
        return courseCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses.course_cover
     *
     * @param courseCover the value for vpro_courses.course_cover
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public void setCourseCover(String courseCover) {
        this.courseCover = courseCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses.course_time
     *
     * @return the value of vpro_courses.course_time
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public String getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses.course_time
     *
     * @param courseTime the value for vpro_courses.course_time
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public void setCourseTime(String courseTime) {
        this.courseTime = courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses.course_status
     *
     * @return the value of vpro_courses.course_status
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public Boolean getCourseStatus() {
        return courseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses.course_status
     *
     * @param courseStatus the value for vpro_courses.course_status
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public void setCourseStatus(Boolean courseStatus) {
        this.courseStatus = courseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses.course_price
     *
     * @return the value of vpro_courses.course_price
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public BigDecimal getCoursePrice() {
        return coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses.course_price
     *
     * @param coursePrice the value for vpro_courses.course_price
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public void setCoursePrice(BigDecimal coursePrice) {
        this.coursePrice = coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses.course_discount_price
     *
     * @return the value of vpro_courses.course_discount_price
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public BigDecimal getCourseDiscountPrice() {
        return courseDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses.course_discount_price
     *
     * @param courseDiscountPrice the value for vpro_courses.course_discount_price
     *
     * @mbg.generated Tue Jan 08 13:35:00 CST 2019
     */
    public void setCourseDiscountPrice(BigDecimal courseDiscountPrice) {
        this.courseDiscountPrice = courseDiscountPrice;
    }
}