package com.mark.manager.pojo;

public class VproAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_auth.auth_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private Integer authId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_auth.auth_appid
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private String authAppid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_auth.auth_appkey
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private String authAppkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_auth.auth_time
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private String authTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_auth.auth_token
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private String authToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_auth.auth_ip
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private String authIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_auth.auth_nkname
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private String authNkname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_auth.auth_roles_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    private Integer authRolesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_auth.auth_id
     *
     * @return the value of vpro_auth.auth_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public Integer getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_auth.auth_id
     *
     * @param authId the value for vpro_auth.auth_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_auth.auth_appid
     *
     * @return the value of vpro_auth.auth_appid
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public String getAuthAppid() {
        return authAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_auth.auth_appid
     *
     * @param authAppid the value for vpro_auth.auth_appid
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setAuthAppid(String authAppid) {
        this.authAppid = authAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_auth.auth_appkey
     *
     * @return the value of vpro_auth.auth_appkey
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public String getAuthAppkey() {
        return authAppkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_auth.auth_appkey
     *
     * @param authAppkey the value for vpro_auth.auth_appkey
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setAuthAppkey(String authAppkey) {
        this.authAppkey = authAppkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_auth.auth_time
     *
     * @return the value of vpro_auth.auth_time
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public String getAuthTime() {
        return authTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_auth.auth_time
     *
     * @param authTime the value for vpro_auth.auth_time
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setAuthTime(String authTime) {
        this.authTime = authTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_auth.auth_token
     *
     * @return the value of vpro_auth.auth_token
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_auth.auth_token
     *
     * @param authToken the value for vpro_auth.auth_token
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_auth.auth_ip
     *
     * @return the value of vpro_auth.auth_ip
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public String getAuthIp() {
        return authIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_auth.auth_ip
     *
     * @param authIp the value for vpro_auth.auth_ip
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setAuthIp(String authIp) {
        this.authIp = authIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_auth.auth_nkname
     *
     * @return the value of vpro_auth.auth_nkname
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public String getAuthNkname() {
        return authNkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_auth.auth_nkname
     *
     * @param authNkname the value for vpro_auth.auth_nkname
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setAuthNkname(String authNkname) {
        this.authNkname = authNkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_auth.auth_roles_id
     *
     * @return the value of vpro_auth.auth_roles_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public Integer getAuthRolesId() {
        return authRolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_auth.auth_roles_id
     *
     * @param authRolesId the value for vpro_auth.auth_roles_id
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setAuthRolesId(Integer authRolesId) {
        this.authRolesId = authRolesId;
    }
}