package com.mark.manager.pojo;

import java.util.ArrayList;
import java.util.List;

public class VproPermissionsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public VproPermissionsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPermissionsIdIsNull() {
            addCriterion("permissions_id is null");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdIsNotNull() {
            addCriterion("permissions_id is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdEqualTo(Integer value) {
            addCriterion("permissions_id =", value, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdNotEqualTo(Integer value) {
            addCriterion("permissions_id <>", value, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdGreaterThan(Integer value) {
            addCriterion("permissions_id >", value, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("permissions_id >=", value, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdLessThan(Integer value) {
            addCriterion("permissions_id <", value, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdLessThanOrEqualTo(Integer value) {
            addCriterion("permissions_id <=", value, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdIn(List<Integer> values) {
            addCriterion("permissions_id in", values, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdNotIn(List<Integer> values) {
            addCriterion("permissions_id not in", values, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdBetween(Integer value1, Integer value2) {
            addCriterion("permissions_id between", value1, value2, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("permissions_id not between", value1, value2, "permissionsId");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameIsNull() {
            addCriterion("permissions_name is null");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameIsNotNull() {
            addCriterion("permissions_name is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameEqualTo(String value) {
            addCriterion("permissions_name =", value, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameNotEqualTo(String value) {
            addCriterion("permissions_name <>", value, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameGreaterThan(String value) {
            addCriterion("permissions_name >", value, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameGreaterThanOrEqualTo(String value) {
            addCriterion("permissions_name >=", value, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameLessThan(String value) {
            addCriterion("permissions_name <", value, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameLessThanOrEqualTo(String value) {
            addCriterion("permissions_name <=", value, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameLike(String value) {
            addCriterion("permissions_name like", value, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameNotLike(String value) {
            addCriterion("permissions_name not like", value, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameIn(List<String> values) {
            addCriterion("permissions_name in", values, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameNotIn(List<String> values) {
            addCriterion("permissions_name not in", values, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameBetween(String value1, String value2) {
            addCriterion("permissions_name between", value1, value2, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsNameNotBetween(String value1, String value2) {
            addCriterion("permissions_name not between", value1, value2, "permissionsName");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidIsNull() {
            addCriterion("permissions_pid is null");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidIsNotNull() {
            addCriterion("permissions_pid is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidEqualTo(Integer value) {
            addCriterion("permissions_pid =", value, "permissionsPid");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidNotEqualTo(Integer value) {
            addCriterion("permissions_pid <>", value, "permissionsPid");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidGreaterThan(Integer value) {
            addCriterion("permissions_pid >", value, "permissionsPid");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("permissions_pid >=", value, "permissionsPid");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidLessThan(Integer value) {
            addCriterion("permissions_pid <", value, "permissionsPid");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidLessThanOrEqualTo(Integer value) {
            addCriterion("permissions_pid <=", value, "permissionsPid");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidIn(List<Integer> values) {
            addCriterion("permissions_pid in", values, "permissionsPid");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidNotIn(List<Integer> values) {
            addCriterion("permissions_pid not in", values, "permissionsPid");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidBetween(Integer value1, Integer value2) {
            addCriterion("permissions_pid between", value1, value2, "permissionsPid");
            return (Criteria) this;
        }

        public Criteria andPermissionsPidNotBetween(Integer value1, Integer value2) {
            addCriterion("permissions_pid not between", value1, value2, "permissionsPid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_permissions
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 18 10:09:12 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vpro_permissions
     *
     * @mbg.generated Thu Oct 18 10:09:12 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}