package com.mark.manager.pojo;

public class VproCoursesLessonList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_lesson_list.lesson_id
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    private String lessonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_lesson_list.lesson_lid
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    private String lessonLid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_lesson_list.lesson_pid
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    private String lessonPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_lesson_list.lesson_title
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    private String lessonTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_lesson_list.lesson_is_chapter_head
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    private String lessonIsChapterHead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_lesson_list.lesson_course_id
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    private String lessonCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_courses_lesson_list.lesson_is_deleted
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    private String lessonIsDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_lesson_list.lesson_id
     *
     * @return the value of vpro_courses_lesson_list.lesson_id
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public String getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_lesson_list.lesson_id
     *
     * @param lessonId the value for vpro_courses_lesson_list.lesson_id
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public void setLessonId(String lessonId) {
        this.lessonId = lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_lesson_list.lesson_lid
     *
     * @return the value of vpro_courses_lesson_list.lesson_lid
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public String getLessonLid() {
        return lessonLid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_lesson_list.lesson_lid
     *
     * @param lessonLid the value for vpro_courses_lesson_list.lesson_lid
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public void setLessonLid(String lessonLid) {
        this.lessonLid = lessonLid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_lesson_list.lesson_pid
     *
     * @return the value of vpro_courses_lesson_list.lesson_pid
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public String getLessonPid() {
        return lessonPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_lesson_list.lesson_pid
     *
     * @param lessonPid the value for vpro_courses_lesson_list.lesson_pid
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public void setLessonPid(String lessonPid) {
        this.lessonPid = lessonPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_lesson_list.lesson_title
     *
     * @return the value of vpro_courses_lesson_list.lesson_title
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public String getLessonTitle() {
        return lessonTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_lesson_list.lesson_title
     *
     * @param lessonTitle the value for vpro_courses_lesson_list.lesson_title
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public void setLessonTitle(String lessonTitle) {
        this.lessonTitle = lessonTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_lesson_list.lesson_is_chapter_head
     *
     * @return the value of vpro_courses_lesson_list.lesson_is_chapter_head
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public String getLessonIsChapterHead() {
        return lessonIsChapterHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_lesson_list.lesson_is_chapter_head
     *
     * @param lessonIsChapterHead the value for vpro_courses_lesson_list.lesson_is_chapter_head
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public void setLessonIsChapterHead(String lessonIsChapterHead) {
        this.lessonIsChapterHead = lessonIsChapterHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_lesson_list.lesson_course_id
     *
     * @return the value of vpro_courses_lesson_list.lesson_course_id
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public String getLessonCourseId() {
        return lessonCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_lesson_list.lesson_course_id
     *
     * @param lessonCourseId the value for vpro_courses_lesson_list.lesson_course_id
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public void setLessonCourseId(String lessonCourseId) {
        this.lessonCourseId = lessonCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_courses_lesson_list.lesson_is_deleted
     *
     * @return the value of vpro_courses_lesson_list.lesson_is_deleted
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public String getLessonIsDeleted() {
        return lessonIsDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_courses_lesson_list.lesson_is_deleted
     *
     * @param lessonIsDeleted the value for vpro_courses_lesson_list.lesson_is_deleted
     *
     * @mbg.generated Sun Dec 16 13:51:30 CST 2018
     */
    public void setLessonIsDeleted(String lessonIsDeleted) {
        this.lessonIsDeleted = lessonIsDeleted;
    }
}