package com.mark.manager.pojo;

public class VproCommentSupportRate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment_support_rate.comment_id
     *
     * @mbg.generated Mon Mar 11 11:25:25 CST 2019
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment_support_rate.comment_agree
     *
     * @mbg.generated Mon Mar 11 11:25:25 CST 2019
     */
    private Integer commentAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vpro_comment_support_rate.comment_oppose
     *
     * @mbg.generated Mon Mar 11 11:25:25 CST 2019
     */
    private Integer commentOppose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment_support_rate.comment_id
     *
     * @return the value of vpro_comment_support_rate.comment_id
     *
     * @mbg.generated Mon Mar 11 11:25:25 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment_support_rate.comment_id
     *
     * @param commentId the value for vpro_comment_support_rate.comment_id
     *
     * @mbg.generated Mon Mar 11 11:25:25 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment_support_rate.comment_agree
     *
     * @return the value of vpro_comment_support_rate.comment_agree
     *
     * @mbg.generated Mon Mar 11 11:25:25 CST 2019
     */
    public Integer getCommentAgree() {
        return commentAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment_support_rate.comment_agree
     *
     * @param commentAgree the value for vpro_comment_support_rate.comment_agree
     *
     * @mbg.generated Mon Mar 11 11:25:25 CST 2019
     */
    public void setCommentAgree(Integer commentAgree) {
        this.commentAgree = commentAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vpro_comment_support_rate.comment_oppose
     *
     * @return the value of vpro_comment_support_rate.comment_oppose
     *
     * @mbg.generated Mon Mar 11 11:25:25 CST 2019
     */
    public Integer getCommentOppose() {
        return commentOppose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vpro_comment_support_rate.comment_oppose
     *
     * @param commentOppose the value for vpro_comment_support_rate.comment_oppose
     *
     * @mbg.generated Mon Mar 11 11:25:25 CST 2019
     */
    public void setCommentOppose(Integer commentOppose) {
        this.commentOppose = commentOppose;
    }
}